# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import instance_manager_pb2 as instance__manager__pb2


class InstanceManagerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.StopInstances = channel.unary_unary(
        '/instance_manager.InstanceManager/StopInstances',
        request_serializer=instance__manager__pb2.StopInstanceRequest.SerializeToString,
        response_deserializer=instance__manager__pb2.InstanceList.FromString,
        )


class InstanceManagerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def StopInstances(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_InstanceManagerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'StopInstances': grpc.unary_unary_rpc_method_handler(
          servicer.StopInstances,
          request_deserializer=instance__manager__pb2.StopInstanceRequest.FromString,
          response_serializer=instance__manager__pb2.InstanceList.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'instance_manager.InstanceManager', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
