# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: instance_manager.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='instance_manager.proto',
  package='instance_manager',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x16instance_manager.proto\x12\x10instance_manager\"&\n\x08Instance\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04zone\x18\x02 \x01(\t\"\x1d\n\x07Project\x12\x12\n\nproject_id\x18\x01 \x01(\t\" \n\x0cZonePrefixes\x12\x10\n\x08prefixes\x18\x01 \x03(\t\"p\n\x13StopInstanceRequest\x12*\n\x07project\x18\x01 \x01(\x0b\x32\x19.instance_manager.Project\x12-\n\x05zones\x18\x02 \x01(\x0b\x32\x1e.instance_manager.ZonePrefixes\"=\n\x0cInstanceList\x12-\n\tinstances\x18\x01 \x03(\x0b\x32\x1a.instance_manager.Instance2k\n\x0fInstanceManager\x12X\n\rStopInstances\x12%.instance_manager.StopInstanceRequest\x1a\x1e.instance_manager.InstanceList\"\x00\x62\x06proto3')
)




_INSTANCE = _descriptor.Descriptor(
  name='Instance',
  full_name='instance_manager.Instance',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='instance_manager.Instance.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='zone', full_name='instance_manager.Instance.zone', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=82,
)


_PROJECT = _descriptor.Descriptor(
  name='Project',
  full_name='instance_manager.Project',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='project_id', full_name='instance_manager.Project.project_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=84,
  serialized_end=113,
)


_ZONEPREFIXES = _descriptor.Descriptor(
  name='ZonePrefixes',
  full_name='instance_manager.ZonePrefixes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='prefixes', full_name='instance_manager.ZonePrefixes.prefixes', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=115,
  serialized_end=147,
)


_STOPINSTANCEREQUEST = _descriptor.Descriptor(
  name='StopInstanceRequest',
  full_name='instance_manager.StopInstanceRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='project', full_name='instance_manager.StopInstanceRequest.project', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='zones', full_name='instance_manager.StopInstanceRequest.zones', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=149,
  serialized_end=261,
)


_INSTANCELIST = _descriptor.Descriptor(
  name='InstanceList',
  full_name='instance_manager.InstanceList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='instances', full_name='instance_manager.InstanceList.instances', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=263,
  serialized_end=324,
)

_STOPINSTANCEREQUEST.fields_by_name['project'].message_type = _PROJECT
_STOPINSTANCEREQUEST.fields_by_name['zones'].message_type = _ZONEPREFIXES
_INSTANCELIST.fields_by_name['instances'].message_type = _INSTANCE
DESCRIPTOR.message_types_by_name['Instance'] = _INSTANCE
DESCRIPTOR.message_types_by_name['Project'] = _PROJECT
DESCRIPTOR.message_types_by_name['ZonePrefixes'] = _ZONEPREFIXES
DESCRIPTOR.message_types_by_name['StopInstanceRequest'] = _STOPINSTANCEREQUEST
DESCRIPTOR.message_types_by_name['InstanceList'] = _INSTANCELIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Instance = _reflection.GeneratedProtocolMessageType('Instance', (_message.Message,), {
  'DESCRIPTOR' : _INSTANCE,
  '__module__' : 'instance_manager_pb2'
  # @@protoc_insertion_point(class_scope:instance_manager.Instance)
  })
_sym_db.RegisterMessage(Instance)

Project = _reflection.GeneratedProtocolMessageType('Project', (_message.Message,), {
  'DESCRIPTOR' : _PROJECT,
  '__module__' : 'instance_manager_pb2'
  # @@protoc_insertion_point(class_scope:instance_manager.Project)
  })
_sym_db.RegisterMessage(Project)

ZonePrefixes = _reflection.GeneratedProtocolMessageType('ZonePrefixes', (_message.Message,), {
  'DESCRIPTOR' : _ZONEPREFIXES,
  '__module__' : 'instance_manager_pb2'
  # @@protoc_insertion_point(class_scope:instance_manager.ZonePrefixes)
  })
_sym_db.RegisterMessage(ZonePrefixes)

StopInstanceRequest = _reflection.GeneratedProtocolMessageType('StopInstanceRequest', (_message.Message,), {
  'DESCRIPTOR' : _STOPINSTANCEREQUEST,
  '__module__' : 'instance_manager_pb2'
  # @@protoc_insertion_point(class_scope:instance_manager.StopInstanceRequest)
  })
_sym_db.RegisterMessage(StopInstanceRequest)

InstanceList = _reflection.GeneratedProtocolMessageType('InstanceList', (_message.Message,), {
  'DESCRIPTOR' : _INSTANCELIST,
  '__module__' : 'instance_manager_pb2'
  # @@protoc_insertion_point(class_scope:instance_manager.InstanceList)
  })
_sym_db.RegisterMessage(InstanceList)



_INSTANCEMANAGER = _descriptor.ServiceDescriptor(
  name='InstanceManager',
  full_name='instance_manager.InstanceManager',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=326,
  serialized_end=433,
  methods=[
  _descriptor.MethodDescriptor(
    name='StopInstances',
    full_name='instance_manager.InstanceManager.StopInstances',
    index=0,
    containing_service=None,
    input_type=_STOPINSTANCEREQUEST,
    output_type=_INSTANCELIST,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_INSTANCEMANAGER)

DESCRIPTOR.services_by_name['InstanceManager'] = _INSTANCEMANAGER

# @@protoc_insertion_point(module_scope)
