# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import project_manager_pb2 as project__manager__pb2


class ProjectManagerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetProjects = channel.unary_unary(
        '/project_manager.ProjectManager/GetProjects',
        request_serializer=project__manager__pb2.GetProjectRequest.SerializeToString,
        response_deserializer=project__manager__pb2.ProjectList.FromString,
        )


class ProjectManagerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetProjects(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ProjectManagerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetProjects': grpc.unary_unary_rpc_method_handler(
          servicer.GetProjects,
          request_deserializer=project__manager__pb2.GetProjectRequest.FromString,
          response_serializer=project__manager__pb2.ProjectList.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'project_manager.ProjectManager', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
