# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: project_manager.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='project_manager.proto',
  package='project_manager',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x15project_manager.proto\x12\x0fproject_manager\"\"\n\x0b\x43redentials\x12\x13\n\x0b\x63redentials\x18\x01 \x01(\t\"+\n\x07Project\x12\x12\n\nproject_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\"F\n\x11GetProjectRequest\x12\x31\n\x0b\x63redentials\x18\x01 \x01(\x0b\x32\x1c.project_manager.Credentials\"9\n\x0bProjectList\x12*\n\x08projects\x18\x01 \x03(\x0b\x32\x18.project_manager.Project2c\n\x0eProjectManager\x12Q\n\x0bGetProjects\x12\".project_manager.GetProjectRequest\x1a\x1c.project_manager.ProjectList\"\x00\x62\x06proto3')
)




_CREDENTIALS = _descriptor.Descriptor(
  name='Credentials',
  full_name='project_manager.Credentials',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='credentials', full_name='project_manager.Credentials.credentials', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=76,
)


_PROJECT = _descriptor.Descriptor(
  name='Project',
  full_name='project_manager.Project',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='project_id', full_name='project_manager.Project.project_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='project_manager.Project.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=78,
  serialized_end=121,
)


_GETPROJECTREQUEST = _descriptor.Descriptor(
  name='GetProjectRequest',
  full_name='project_manager.GetProjectRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='credentials', full_name='project_manager.GetProjectRequest.credentials', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=123,
  serialized_end=193,
)


_PROJECTLIST = _descriptor.Descriptor(
  name='ProjectList',
  full_name='project_manager.ProjectList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='projects', full_name='project_manager.ProjectList.projects', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=195,
  serialized_end=252,
)

_GETPROJECTREQUEST.fields_by_name['credentials'].message_type = _CREDENTIALS
_PROJECTLIST.fields_by_name['projects'].message_type = _PROJECT
DESCRIPTOR.message_types_by_name['Credentials'] = _CREDENTIALS
DESCRIPTOR.message_types_by_name['Project'] = _PROJECT
DESCRIPTOR.message_types_by_name['GetProjectRequest'] = _GETPROJECTREQUEST
DESCRIPTOR.message_types_by_name['ProjectList'] = _PROJECTLIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Credentials = _reflection.GeneratedProtocolMessageType('Credentials', (_message.Message,), {
  'DESCRIPTOR' : _CREDENTIALS,
  '__module__' : 'project_manager_pb2'
  # @@protoc_insertion_point(class_scope:project_manager.Credentials)
  })
_sym_db.RegisterMessage(Credentials)

Project = _reflection.GeneratedProtocolMessageType('Project', (_message.Message,), {
  'DESCRIPTOR' : _PROJECT,
  '__module__' : 'project_manager_pb2'
  # @@protoc_insertion_point(class_scope:project_manager.Project)
  })
_sym_db.RegisterMessage(Project)

GetProjectRequest = _reflection.GeneratedProtocolMessageType('GetProjectRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETPROJECTREQUEST,
  '__module__' : 'project_manager_pb2'
  # @@protoc_insertion_point(class_scope:project_manager.GetProjectRequest)
  })
_sym_db.RegisterMessage(GetProjectRequest)

ProjectList = _reflection.GeneratedProtocolMessageType('ProjectList', (_message.Message,), {
  'DESCRIPTOR' : _PROJECTLIST,
  '__module__' : 'project_manager_pb2'
  # @@protoc_insertion_point(class_scope:project_manager.ProjectList)
  })
_sym_db.RegisterMessage(ProjectList)



_PROJECTMANAGER = _descriptor.ServiceDescriptor(
  name='ProjectManager',
  full_name='project_manager.ProjectManager',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=254,
  serialized_end=353,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetProjects',
    full_name='project_manager.ProjectManager.GetProjects',
    index=0,
    containing_service=None,
    input_type=_GETPROJECTREQUEST,
    output_type=_PROJECTLIST,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PROJECTMANAGER)

DESCRIPTOR.services_by_name['ProjectManager'] = _PROJECTMANAGER

# @@protoc_insertion_point(module_scope)
